# Generated by Django 5.2.10 on 2026-01-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naukri_job_id', models.BigIntegerField(db_index=True, unique=True)),
                ('job_url', models.URLField(max_length=1000, unique=True)),
                ('resume_match', models.BooleanField(null=True)),
                ('scrape_status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('chatbot_status', models.CharField(db_index=True, default='unknown', max_length=20)),
                ('apply_status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scrape_status'], name='jobs_job_scrape__780779_idx'), models.Index(fields=['chatbot_status'], name='jobs_job_chatbot_2d8efa_idx'), models.Index(fields=['apply_status'], name='jobs_job_apply_s_29ff93_idx')],
            },
        ),
    ]
