# Generated by Django 5.2.10 on 2026-01-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='chatbot_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='scrape_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
